# -*- coding: utf-8 -*-
"""Neural Network Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fq0zWpsg1M2lKybtP7xSCkZcFeUiNa-5
"""

import numpy as np
a = [9, 3, 3, 5]
print(np.array(a))

import numpy as np
n = np.array([9, 3, 3, 5])
print(n.mean())

import numpy as np
a = np.array([5, 72, 13, 100])
b = np. array([2, 5, 10, 30])
res = np.add(a, b)
print (res)

res2 = np.subtract(a, b)
print (res2)

res3 = np.multiply(a, b)
print (res3)

res4 = np.divide(a, b)
print (res4)

res5 = np.power(a, b)
print (res5)

res6 = np.mod(a, b)
print (res6)

import numpy as np
arr = np.array([[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]])
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
print(np.sum(arr, axis = 1, keepdims = True))

import numpy as np
arr = np.array([[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))
print(np.min(arr, axis = 1, keepdims = True))

import numpy as np
arr = np.array([[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))
print(np.max(arr, axis = 1, keepdims = True))

import numpy as np
arr = np.array([[14, 17, 12, 33, 44], [15, 6, 27, 8, 19], [23, 2, 54, 1, 4]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))
print(np.mean(arr, axis = 1, keepdims = True))

import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("Square root:\n", np.sqrt(x))
print("Sum of all elements:", np.sum(y))

print("Column-wise sum:", np.sum(y, axis = 0))
print("Row-wise sum:", np.sum(y, axis = 1))
print("Transpose:\n", x.T)

import numpy as np
arr = [0, np.pi/2, np.pi/3, np.pi]

s1 = np.sin(arr)
print("Sine values:\n", s1)

s2 = np.cos(arr)
print("\nCosine values:\n", s2)

s3 = np.tan(arr)
print("\nTangent values:\n", s3)

import matplotlib.pyplot as plt
import numpy as np
x = np.array([1, 2, 3, 4])
y = x*2
plt.plot(x, y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
fruits = ['Apples', 'Bananas', 'Cherries', 'Dates']
sales = [400, 350, 300, 450]
plt.bar(fruits, sales)
plt.title('Fruit Sales')
plt.xlabel('Fruit')
plt.ylabel('Sales')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.array([12, 45, 7, 32, 89, 54, 23, 67, 14, 91])
y = np.array([99, 31, 72, 56, 19, 88, 43, 61, 35, 77])

plt.scatter(x, y)
plt.title('Basic Scatter Plot')
plt.xlabel('X values')
plt.ylabel('Y values')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

data = np.random.randn(1000)
plt.hist(data, bins = 30, color='skyblue', edgecolor='black')
plt.title('Basic Histogram')
plt.xlabel('Values')
plt.ylabel('Frequency')
plt.show()



from matplotlib import pyplot as plt
import numpy as np

cars = ['AUDI', 'BMW', 'FORD', 'TESLA', 'JAGUAR', 'MERCEDES']

data = [23, 17, 35, 29, 12, 41]

fig = plt.figure(figsize = (10, 7))
plt.pie(data, labels = cars)
plt.show()

import numpy as np

a = np.array([1, 2, 3])
print(type(a), a.shape, a[0], a[1], a[2])

a[0] = 5
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

a = np.zeros((2, 2))
print(a)

b = np.ones((1, 2))
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2, 2))
print(e)

a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])


b = a[:2, 1:3]
print(b)

print(a[0, 1])

b[0, 0] = 77
print(a[0, 1])

row_r1 = a[1, :]

row_r2 = a[1:2, :]

row_r3 = a[[1], :]

print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,), and
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

# Create a new array from which we will select elements
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])
print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

import numpy as np

a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

# Find the elements of a that are bigger than 2; this returns a NumPy array
# of Booleans of the same shape as a, where each slot of bool_idx
# tells whether that element of a is > 2.
bool_idx = (a > 2)

print(bool_idx)

# We use boolean array indexing to construct a rank 1 array consisting
# of the elements of a corresponding to the True values of bool_idx
print(a[bool_idx])

x = np.array([[1, 2],
              [3, 4]], dtype=np.float64)
y = np.array([[5, 6],
              [7, 8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
print(np.sqrt(x))

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

x = np.array([[1, 2],
              [3, 4]])

# Compute sum of all elements
print(np.sum(x))

# Compute sum of each column
print(np.sum(x, axis=0))

# Compute sum of each row
print(np.sum(x, axis=1))

# Transpose
print(x)
print(x.T)

import numpy as np

x = np.array([[1, 2, 3],
              [4, 5, 6]])

v = np.array([1, 2, 3])

y = x + v
print(y)

v_col = np.array([1, 2])
y_col = x + v_col.reshape(2, 1)
print(y_col)

v_outer = np.array([1, 2, 3])
w_outer = np.array([4, 5])
print(v_outer.reshape(3, 1) * w_outer)

x2 = np.array([[1, 2, 3],
               [4, 5, 6]])

v2 = np.array([1, 2])
print((x2.T + v2).T)

#Import the numpy package under the name np and print the numpy version and the configuration.
import numpy as np
print(np.__version__)
np.show_config()

#Convert a list of numeric value into a one-dimensional NumPy array
import numpy as np
a = np.array([1, 2, 3, 4, 5])
print(a)

#Create a null vector of size 5
import numpy as np
a = np.zeros(5)
print(a)

#Create a null vector of size 12 but the fourth value which is 100
import numpy as np
a = np.zeros(12)
a[3] = 100
print(a)

#Create a vector with values ranging from 29 to 60
import numpy as np
a = np.arange(29, 61)
print(a)

#Create a 3×3 matrix with values ranging from 50 to 58
import numpy as np
a = np.arange(50, 59).reshape(3, 3)
print(a)

#Find indices of non-zero elements from [5,8,0,9,0,0]
import numpy as np
a = np.array([5, 8, 0, 9, 0, 0])
print(np.nonzero(a))

#Create a 5×5 identity matrix
import numpy as np
a = np.eye(5)
print(a)

#Create a 3×3×3 array with random values
import numpy as np
a = np.random.random((3, 3, 3))
print(a)

#Create a 9×9 array with random values and find the minimum and maximum values
import numpy as np
a = np.random.random((9, 9))
print(a.min(), a.max())

#Create a random vector of size 20 and find the mean value
import numpy as np
a = np.random.random(20)
print(a.mean())

#Create a 6×6 matrix with values 1,2,3,4 just below the diagonal
import numpy as np
a = np.zeros((6, 6))
np.fill_diagonal(a[1:], [1, 2, 3, 4, 1])
print(a)

#Consider a (8,9,10) shape array, what is the index (x,y,z) of the 100th element?
import numpy as np
print(np.unravel_index(99, (8, 9, 10)))

#Consider two random arrays A and B, check if they are equal
import numpy as np
A = np.random.random((3, 3))
B = np.random.random((3, 3))
print(np.array_equal(A, B))

#How to sort an array of shape (5,4) by the nth column?
import numpy as np
a = np.random.randint(0, 10, (5, 4))
n = 2
print(a[a[:, n].argsort()])

#Consider an array a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], generate an array
#b = [[1,2,3,4],[2,3,4,5],[3,4,5,6],…,[11,12,13,14]]
import numpy as np
a = np.arange(1, 15)
b = np.array([a[i:i+4] for i in range(11)])
print(b)

#How to find the most frequent value in an array?
import numpy as np
a = np.array([1, 2, 2, 3, 4, 2, 5])
values, counts = np.unique(a, return_counts=True)
print(values[np.argmax(counts)])

import pandas as pd

student_dict = {'Name': ['Joe', 'Nat'], 'Age': [20, 21], 'Marks': [85.10, 77.80]}
print(student_dict)

student_df = pd.DataFrame(student_dict)
print(student_df)

df = pd.DataFrame(
    {'A': [1, 2, 3],
     'B': [True, True, False],
     'C': [0.496714, -0.138264, 0.647689]},
    index=['a', 'b', 'c']
)
print(df)

fruits_list = ['Apple', 'Banana', 'Orange', 'Mango']
print(fruits_list)

fruits_df = pd.DataFrame(fruits_list, columns=['Fruits'])
print(fruits_df)

fruits_list = [['Apple', 'Banana', 'Orange', 'Mango'],
               [120, 40, 80, 500]]
print(fruits_list)

fruits_df = pd.DataFrame(fruits_list)
print(fruits_df)

fruits_list = [['Apple', 'Banana', 'Orange', 'Mango'],
               [120, 40, 80, 500]]
print(fruits_list)

fruits_df = pd.DataFrame(fruits_list).transpose()
print(fruits_df)

fruits_list = ['Apple', 'Banana', 'Orange', 'Mango']
price_list = [120, 40, 80, 500]

fruits_df = pd.DataFrame(list(zip(fruits_list, price_list)),
                         columns=['Name', 'Price'])
print(fruits_df)

df['A']

cols = ['A', 'C']
df[cols]

df.loc[['a', 'b']]

df.loc['a':'b']

df.iloc[[0, 1]]

df.iloc[:2]

df.loc['a', 'B']

df.loc['a':'b', ['A', 'C']]

cars = pd.read_csv("/content/sample_data/automobile_cleaned.csv")
print(cars)

pd.options.display.max_rows = 20
pd.set_option("display.min_rows", 10)

print(cars)
cars.info()
cars.describe()

student_dict = {'Name': ['Joe', 'Nat', 'Harry'],
                'Age': [20, 21, 19],
                'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)

print("DataFrame : ", student_df)
print("DataFrame Index : ", student_df.index)
print("DataFrame Columns : ", student_df.columns)
print("DataFrame Column types : ", student_df.dtypes)
print("DataFrame is empty? : ", student_df.empty)
print("DataFrame Shape : ", student_df.shape)
print("DataFrame Size : ", student_df.size)
print("DataFrame Values : ", student_df.values)

print("DataFrame : ", student_df)

print(student_df.head(2))

print(student_df.tail(2))

print(student_df.at[0, 'Name'])

print(student_df.iat[0, 0])

print(student_df.get('Name'))

print(student_df.loc[0:2, ['Name']])

print(student_df.iloc[0:2, 0:2])

student_dict = {'Name': ['Joe', 'Nat', 'Harry'],
                'Age': [20, 21, 19],
                'Marks': [85.10, 77.80, 91.54]}
student_df = pd.DataFrame(student_dict)
print(student_df)

student_df.insert(loc=2, column="Class", value='A')
print(student_df)

student_df = student_df.drop(columns='Age')
print(student_df)

student_dict = {'Name': ['Joe', 'Nat', 'Harry'],
                'Age': [20, 21, 19],
                'Marks': [85.10, 77.80, 91.54]}

student_df = pd.DataFrame(student_dict)
print(student_df)

filter = student_df['Marks'] > 80

student_df['Marks'].where(filter, other=0, inplace=True)
print(student_df)

student_dict = {'Name': ['Joe', 'Nat'], 'Age': [20, 21]}
student_df = pd.DataFrame(student_dict)
print(student_df)

marks_dict = {'Marks': [85.10, 77.80]}
marks_df = pd.DataFrame(marks_dict)
print(marks_df)

joined_df = student_df.join(marks_df)
print(joined_df)

import pandas as pd

student_dict = {
    'Name': ['Joe', 'Nat', 'Harry'],
    'Class': ['A', 'B', 'A'],
    'Marks': [85.10, 77.80, 91.54]
}

student_df = pd.DataFrame(student_dict)
print(student_df)

result = student_df.groupby('Class')['Marks'].mean()
print(result)

student_dict = {'Name': ['Joe', 'Nat'],
                'Age': [20, 21],
                'Marks': [85, 77]}

student_df = pd.DataFrame(student_dict)

for index, row in student_df.iterrows():
    print(index, row)

import pandas as pd
df = pd.read_csv("/content/sample_data/automobile_cleaned.csv")
print(df.head())
print(df.tail())

df = df.dropna()
df.to_csv("automobile_data.csv", index=False)

max_company = df.loc[df['price'].idxmax(), 'company']
min_company = df.loc[df['price'].idxmin(), 'company']
print(max_company, min_company)

print(df[df['company'] == 'bmw'])

print(df['body-style'].value_counts())

print(df.groupby('company')['price'].agg(['max', 'min']))

print(df.groupby('company')['average-mileage'].mean())

print(df.sort_values(by=['price', 'horsepower']))

print(df[(df['wheel-base'] >= 85) & (df['wheel-base'] <= 90)])

df.loc[59, 'price'] = 13240
print(df.loc[59])

print(df['price'].sum())

df.loc[30] = df.iloc[0]
print(df.loc[30])
df = df.drop(30)

import scipy
print(scipy.__version__)

from scipy import constants

print(constants.pi)

l1 = dir(constants)
for e in l1:
    print(e)

print(constants.minute)
print(constants.hour)
print(constants.day)
print(constants.week)
print(constants.Julian_year)

from scipy.optimize import root
from math import cos

def eqn(x):
    return x + cos(x)

myroot = root(eqn, 0)

print(myroot.x)

from scipy.optimize import minimize

def eqn(x):
    return x**2 + x + 2

mymin = minimize(eqn, 0, method='BFGS')

print(mymin)

import numpy as np
from scipy.sparse import csr_matrix

arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

print(csr_matrix(arr))
print(csr_matrix(arr).data)

arr = np.array([[0, 0, 0],
                [0, 0, 1],
                [1, 0, 2]])

print(csr_matrix(arr))
print(csr_matrix(arr).data)

arr = np.array([[0, 0, 0],
                [0, 0, 1],
                [1, 0, 2]])

print(csr_matrix(arr).count_nonzero())

arr = np.array([[0, 0, 0],
                [0, 0, 1],
                [1, 0, 2]])

mat = csr_matrix(arr)

mat.eliminate_zeros()
print(mat)
print(mat.data)

arr = np.array([[0, 0, 0],
                [0, 0, 1],
                [1, 0, 2]])

mat = csr_matrix(arr)
mat.sum_duplicates()
print(mat)

arr = np.array([[0, 0, 0],
                [0, 0, 1],
                [1, 0, 2]])

newarr = csr_matrix(arr).tocsc()
print(newarr)

import numpy as np
from scipy.sparse.csgraph import connected_components
from scipy.sparse import csr_matrix

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(connected_components(newarr))


from scipy.sparse.csgraph import dijkstra

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(dijkstra(newarr, return_predecessors=True, indices=0))


from scipy.sparse.csgraph import floyd_warshall

arr = np.array([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(floyd_warshall(newarr, return_predecessors=True))


from scipy.sparse.csgraph import bellman_ford

arr = np.array([
    [0, -1, 2],
    [1, 0, 0],
    [2, 0, 0]
])

newarr = csr_matrix(arr)
print(bellman_ford(newarr, return_predecessors=True, indices=0))


from scipy.sparse.csgraph import depth_first_order

arr = np.array([
    [0, 1, 0, 1],
    [1, 1, 1, 1],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
])

newarr = csr_matrix(arr)
print(depth_first_order(newarr, 1))


from scipy.sparse.csgraph import breadth_first_order

arr = np.array([
    [0, 1, 0, 1],
    [1, 1, 1, 1],
    [2, 1, 1, 0],
    [0, 1, 0, 1]
])

newarr = csr_matrix(arr)
print(breadth_first_order(newarr, 1))

import numpy as np
from scipy.spatial import Delaunay
import matplotlib.pyplot as plt

points = np.array([
    [2, 4],
    [3, 4],
    [3, 0],
    [2, 2],
    [4, 1]
])

simplices = Delaunay(points).simplices

plt.triplot(points[:, 0], points[:, 1], simplices)
plt.scatter(points[:, 0], points[:, 1], color='r')

plt.show()



import numpy as np
from scipy.spatial import ConvexHull
import matplotlib.pyplot as plt

points = np.array([
    [2, 4],
    [3, 4],
    [3, 0],
    [2, 2],
    [4, 1],
    [1, 2],
    [5, 0],
    [3, 1],
    [1, 2],
    [0, 2]
])

hull = ConvexHull(points)
hull_points = hull.simplices

plt.scatter(points[:, 0], points[:, 1])
for simplex in hull_points:
    plt.plot(points[simplex, 0], points[simplex, 1], 'k-')

plt.show()

from scipy.spatial.distance import euclidean

p1 = (1, 0)
p2 = (10, 2)

res = euclidean(p1, p2)
print(res)

from scipy.spatial.distance import cityblock

p1 = (1, 0)
p2 = (10, 2)

res = cityblock(p1, p2)
print(res)

from scipy.spatial.distance import cosine

p1 = (1, 0)
p2 = (10, 2)

res = cosine(p1, p2)
print(res)

from scipy.spatial.distance import hamming

p1 = (True, False, True)
p2 = (False, True, True)

res = hamming(p1, p2)
print(res)

from scipy.interpolate import interp1d
import numpy as np

xs = np.arange(10)
ys = 2*xs + 1

interp_func = interp1d(xs, ys)

newarr = interp_func(np.arange(2.1, 3, 0.1))
print(newarr)

import numpy as np

print("NumPy version: ", np.__version__)
print("NumPy configuration: ", np.show_config())

num_list = [1, 2, 3, 4, 5]
np_array = np.array(num_list)
print(np_array)

null_vector = np.zeros(5)
print(null_vector)

null_vector = np.zeros(12)
null_vector[3] = 100
print(null_vector)

range_vector = np.arange(29, 61)
print(range_vector)

matrix_3x3 = np.arange(50, 59).reshape(3, 3)
print(matrix_3x3)

arr = np.array([5, 8, 0, 9, 0, 0])
non_zero_indices = np.nonzero(arr)
print(non_zero_indices)

identity_matrix = np.identity(5)
print(identity_matrix)

random_array = np.random.rand(3, 3, 3)
print(random_array)

random_array = np.random.rand(9, 9)
min_val = np.min(random_array)
max_val = np.max(random_array)
print("Minimum value: ", min_val)
print("Maximum value: ", max_val)

random_array = np.random.rand(20)
mean_val = np.mean(random_array)
print("Mean value: ", mean_val)

matrix_6x6 = np.diag(1 + np.arange(4), k=-1)
print(matrix_6x6)

shape_array = np.zeros((8, 9, 10))
x, y, z = np.unravel_index(99, shape_array.shape)
print("Index of 100th element: ", x, y, z)

array_A = np.random.rand(3, 3)
array_B = np.random.rand(3, 3)
equal_arrays = np.array_equal(array_A, array_B)
print("Are the arrays equal? ", equal_arrays)

array_5x4 = np.random.rand(5, 4)
print("Array before sorting: \n", array_5x4)
nth_column = 1
sorted_array = array_5x4[array_5x4[:, nth_column].argsort()]
print("Array after sorting by the nth column: \n", sorted_array)

a = np.arange(1, 15)
b = np.array([a[i:i+4] for i in range(0, len(a)-3)])
print(b)

array = np.array([1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 5])
values, counts = np.unique(array, return_counts=True)
index = np.argmax(counts)
most_frequent_value = values[index]
print("Most frequent value: ", most_frequent_value)

import pandas as pd

file_path = '/content/sample_data/automobile.csv'

with open(file_path, 'r') as f:
    auto_df = pd.read_csv(f)

print("First five rows of the automobile dataset:")
print(auto_df.head())
print("\nLast five rows of the automobile dataset:")
print(auto_df.tail())

auto_df.replace('?', pd.NA, inplace=True)
auto_df.dropna(inplace=True)
auto_df.to_csv('automobile_cleaned.csv', index=False)

most_expensive_company = auto_df.loc[auto_df.price.idxmax(), 'company']
print(f"\nThe most expensive car company is {most_expensive_company}.")

least_expensive_company = auto_df.loc[auto_df.price.idxmin(), 'company']
print(f"\nThe least expensive car company is {least_expensive_company}.")

bmw_cars = auto_df[auto_df.company == 'bmw']
print("\nDetails of all BMW cars:")
print(bmw_cars)

body_style_counts = auto_df['body-style'].value_counts()
print("\nTotal cars per body-style:")
print(body_style_counts)

grouped = auto_df.groupby('company')['price']
result = pd.DataFrame({
    'Highest price': grouped.max(),
    'Lowest price': grouped.min()
})
print("\nEach company's highest and lowest price cars:")
print(result)

company_mileage = auto_df.groupby('company')['average-mileage'].mean()
print("\nAverage mileage of each car making company:")
print(company_mileage)

sorted_cars = auto_df.sort_values(['price', 'horsepower'], ascending=[True, False])
print("\nAll cars sorted by price horsepower:")
print(sorted_cars)

selected_rows = auto_df.loc[[13, 24, 58], ['horsepower', 'body-style', 'price']]
print("\nSelected data rows:")
print(selected_rows)

selected_rows = auto_df.query('85 <= `wheel-base` <= 90')
print("\nRows with wheel-base between 85 and 90:")
print(selected_rows)

auto_df.at[59, 'price'] = 13240
print("\nPrice in row 59 updated to 13240.")
print(auto_df.loc[59])

prices_sum = auto_df['price'].sum()
print("\nSum of all prices:", prices_sum)

new_row_data = [89, 'volvo', 'wagon', 104.3, 188.8, 'ohc', 'four', 114, 23, 15000.0]
new_row_df = pd.DataFrame([new_row_data], columns=auto_df.columns)
auto_df = pd.concat([auto_df, new_row_df], ignore_index=True)

print("\nDataFrame with the new row:")
print(auto_df.tail())

auto_df.drop(index=len(auto_df)-1, inplace=True)
print("\nDataFrame after deleting the new row:")
print(auto_df.tail())

import numpy as np

# Define the input features and labels for the logic gates
and_features = np.array([[0,0],[0,1],[1,0],[1,1]])
or_features = np.array([[0,0],[0,1],[1,0],[1,1]])
xor_features = np.array([[0,0],[0,1],[1,0],[1,1]])

and_labels = np.array([0,0,0,1])
or_labels = np.array([0,1,1,1])
xor_labels = np.array([0,1,1,0])

# Define the step function that returns 1 if the input is greater than or equal to 0, else 0
def step_fun(sum):
    return np.where(sum >= 0, 1, 0)

# Initialize the weights and bias for the perceptron algorithm
w = np.random.rand(2)
bias = np.random.rand()

# Define the learning rate and the number of epochs for the algorithm
alpha = 0.1
max_epochs = 1000

print("\nWeight: ", w)
print("Bias: ", bias)
print("Alpha: ", alpha)
print("Epoch: ", max_epochs)

# Implement the perceptron algorithm using vectorized operations (instead of a nested loop) - Calculate the predicted values for all input features at once
def perceptron(features, labels, operator):
    global w, bias

    for i in range(max_epochs):
        print("\nEpoch Value: ", i+1)

        # sum = features[j][0]*w[0] + features[j][1]*w[1] + bias
        sum = np.dot(features, w) + bias

        predicted = step_fun(sum)
        delta = labels - predicted

        # Update weights and bias using the delta rule
        # w[k] += delta * alpha * features[j][k]
        w += alpha * np.dot(features.T, delta)

        # More Efficient Stopping Criterion
        bias += alpha * np.sum(delta)
        error = np.mean(np.abs(delta))

        for j in range(len(features)):
            print(features[j][0], "", operator, "", features[j][1], "-> Actual:", labels[j], "; Predicted:", predicted[j], " ( w1:", w[0], "& w2:", w[1], ")")

        # Terminate the algorithm if all the predicted values are correct
        if error == 0:
            break

# Run the perceptron algorithm for different logic gates
while True:
    operator = str(input("\nEnter Logical Operator (and, or, xor, exit): "))

    if operator == "and":
        perceptron(and_features, and_labels, operator)
    elif operator == "or":
        perceptron(or_features, or_labels, operator)
    elif operator == "xor":
        perceptron(xor_features, xor_labels, operator)

    elif operator == "exit":
        break
    else:
        print("Invalid Input.\nTry Again!")

import numpy as np

# Define the input features and labels for the AND logic gate
and_features = np.array([[0,0],[0,1],[1,0],[1,1]])
and_labels = np.array([0,0,0,1])

# Define the step function which returns 1 if the input is greater than or equal to 0, otherwise 0
def step_fun(sum):
    return np.where(sum >= 0, 1, 0)

# Initialize the weights and bias for the perceptron algorithm
w = np.array([1,1])
bias = -1.5

# Print the initialized weights and bias
print("\nWeight: ", w)
print("Bias: ", bias)
print("\n")

# Implement the perceptron algorithm using vectorized operations (instead of a nested loop)
# Calculate the predicted values for all input features at once
def perceptron(features):
    sum = np.dot(features, w) + bias   # Find the weighted sum of inputs and bias
    predicted = step_fun(sum)          # Apply step function to the sum
    return predicted

# Use the perceptron function to find the predicted outputs for AND logic gate
predicted_and = perceptron(and_features)

# Print the actual and predicted outputs along with the corresponding weights for each input feature
for f, l, p in zip(and_features, and_labels, predicted_and):
    print(f[0], " and ", f[1], " -> Actual: ", l, "; Predicted: ", p, " ( w1: ", w[0], "& w2: ", w[1], ")")

import numpy as np

# Define input features and labels for the NOT logic gate
not_features = np.array([[0,1]])
not_labels = np.array([[1,0]])

# Define step function to be used in perceptron algorithm
def step_function(sums):
    # Return 1 if the input is greater than or equal to 0, otherwise return 0
    return np.where(sums >= 0, 1, 0)

# Initialize weights and bias values for perceptron algorithm
w = -1
bias = 0.5

# Print initialized weights and bias values
print("\nWeights:", w)
print("Bias:", bias)
print("\n")

# Implement perceptron algorithm using vectorized operations
def perceptron(features, labels, weights, bias):

    # Calculate the weighted sum of inputs and bias
    sums = np.dot(features, weights) + bias

    # Apply step function to each element of the sum
    predicted = step_function(sums)

    # Return the predicted output
    return predicted

# Use perceptron algorithm to calculate predicted output for given features and labels
predicted_output = perceptron(not_features, not_labels, w, bias)

# Print the input features, actual output, and predicted output
print("Input Features:", not_features)
print("Actual Output:", not_labels)
print("Predicted Output:", predicted_output)

import numpy as np

# Define the input features and labels for the logic gate
or_features = np.array([[0,0],[0,1],[1,0],[1,1]])
or_labels = np.array([0,1,1,1])

# Define the step function that returns 1 if the input is greater than or equal to 0, else 0
def step_function(z):
    return np.where(z >= 0, 1, 0)

# Implement the perceptron algorithm using vectorized operations (instead of a nested loop) - Calculate the predicted values for all input features at once
def perceptron(features, labels, weights, bias_value, operator):

    # Calculate the weighted sum of inputs and apply the bias
    z = np.dot(features, weights) + bias_value

    # Apply the step function to get the predicted values
    predicted = step_function(z)

    # Print the results for each input pair
    for x_input, y_output, prediction in zip(features, labels, predicted):
        print(f"{x_input[0]} {operator} {x_input[1]} -> Actual: {y_output}; Predicted: {prediction} (Weights: {weights[0]} & {weights[1]}, Bias: {bias_value})")

# Initialize the weights and bias for the perceptron algorithm
weights = np.array([1, 1])
bias_value = -0.5

# Print the weight and bias values
print("Weights: ", weights)
print("Bias: ", bias_value)

# Call the perceptron function with input features, labels, weights, bias, and operator type
perceptron(or_features, or_labels, weights, bias_value, "or")

# This code generates data for binary classification and applies different activation functions on it to visualize their outputs

import matplotlib.pyplot as plt
import numpy as np

# Define activation functions
def sigmoid(x):
    """
    Returns the output of the sigmoid function for a given input x.
    """
    return 1 / (1 + np.exp(-x))

def relu(x):
    """
    Returns the output of the ReLU function for a given input x.
    """
    return np.maximum(0, x)

def linear(x):
    """
    Returns the output of the Linear function for a given input x.
    """
    return x

# Generate data for binary classification
input_data = np.random.randn(1000, 2) # Creating a 1000x2 array of random numbers from standard normal distribution
output_labels = (input_data.sum(axis=1) > 0).astype(int) # Creating a binary class label based on sum of each row of input_data

# Plot input data
plt.scatter(input_data[:, 0], input_data[:, 1], c=output_labels) # Plotting scatter plot with first column of input_data as x-axis and second column as y-axis. c=output_labels colors each point according to its corresponding binary class label
plt.title("Input Data") # Setting the title of the plot

plt.xlabel("Feature 1") # Setting the x-label
plt.ylabel("Feature 2") # Setting the y-label
plt.colorbar(label="Class Label") # Adding a colorbar and setting its label
plt.show() # Displaying the plot

# Apply activation functions to input data and store them in a dictionary
activation_functions = {'linear': linear(input_data.sum(axis=1)), 'sigmoid': sigmoid(input_data.sum(axis=1)), 'relu': relu(input_data.sum(axis=1))} # Storing the outputs of all activation functions evaluated at sum of rows of input_data in a dictionary

# Plot output of activation functions
fig, axs = plt.subplots(1, 3, sharey=True, figsize=(12, 4)) # Creating a figure with one row and three columns of subplots, sharing y-axis and setting the size of the figure

for ax, activation_function_name in zip(axs, activation_functions.keys()): # Iterating through each subplot and its corresponding activation function name

    scatter = ax.scatter(input_data[:, 0], input_data[:, 1], c=activation_functions[activation_function_name]) # Plotting the scatter plot with first column of input_data as x-axis and second column as y-axis. c = activation_functions[activation_function_name] colors each point according to the output of respective activation function

    if scatter.get_offsets().size > 0: # Checking if any scatter points are present in the current subplot

        ax.set_title(f"{activation_function_name.capitalize()} Activation") # Setting the title of the subplot with the capitalized name of respective activation function

        ax.set_xlabel("Feature 1") # Setting the x-label for each subplot

fig.tight_layout() # Automatically adjust the subplot parameters to give specified padding between plots.

# Creating a global colorbar only if scatter points are present in any of the subplots
if scatter.get_offsets().size > 0:
    plt.colorbar(scatter, ax=axs.ravel().tolist(), label="Activation Output") # Adding a global colorbar and setting its label

plt.show() # Displaying the plot

import numpy as np

def mse_loss(y_true, y_pred):
    return np.mean((y_true - y_pred) ** 2)

# Example
y_true = np.array([3, -0.5, 2, 7])
y_pred = np.array([2.5, 0.0, 2, 8])

print("MSE:", mse_loss(y_true, y_pred))

import torch
import torch.nn as nn

loss_fn = nn.MSELoss()

y_true = torch.tensor([3.0, -0.5, 2.0, 7.0])
y_pred = torch.tensor([2.5, 0.0, 2.0, 8.0])

loss = loss_fn(y_pred, y_true)
print(loss)

def mae_loss(y_true, y_pred):
    return np.mean(np.abs(y_true - y_pred))

def binary_cross_entropy(y_true, y_pred):
    epsilon = 1e-15  # to avoid log(0)
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    return -np.mean(
        y_true * np.log(y_pred) +
        (1 - y_true) * np.log(1 - y_pred)
    )

def categorical_cross_entropy(y_true, y_pred):
    epsilon = 1e-15
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)

    return -np.sum(y_true * np.log(y_pred)) / y_true.shape[0]

import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Step 1: Generate sample data
np.random.seed(0)
X = np.linspace(-3, 3, 30)
y = np.sin(X) + np.random.normal(0, 0.2, size=X.shape)

X = X.reshape(-1, 1)

# Step 2: Function to train and plot model
def plot_model(degree, subplot):
    poly = PolynomialFeatures(degree=degree)
    X_poly = poly.fit_transform(X)

    model = LinearRegression()
    model.fit(X_poly, y)

    X_test = np.linspace(-3, 3, 100).reshape(-1, 1)
    X_test_poly = poly.transform(X_test)
    y_pred = model.predict(X_test_poly)

    plt.subplot(1, 3, subplot)
    plt.scatter(X, y, color='black')
    plt.plot(X_test, y_pred, color='blue')
    plt.title(f"Degree {degree}")

# Step 3: Plot models
plt.figure(figsize=(15, 4))

plot_model(1, 1)   # Underfitting
plot_model(4, 2)   # Good fit
plot_model(15, 3)  # Overfitting

plt.show()

image_path = "/content/Screenshot 2026-04-05 220048.png"

image = tf.io.read_file(image_path)
image = tf.io.decode_jpeg(image, channels=1)
image = tf.image.resize(image, [300, 300])
image = tf.image.convert_image_dtype(image, tf.float32)

print("Original Image Shape:", image.shape)

plt.figure(figsize=(5,5))
plt.imshow(tf.squeeze(image))
plt.title("Original Image")
plt.axis('off')
plt.show()

# Add batch dimension
image = tf.expand_dims(image, axis=0)

def predict(self, data, num_iter=20, threshold=0, asyn=True):
        pred = []
        energies = []
        for s in tqdm(data):
            s = s.copy()
            e_list = [self.energy(s)]
            for _ in range(num_iter):
                if asyn:  # asynchronous update
                    for _ in range(self.num_neuron):
                        i = np.random.randint(self.num_neuron)
                        s[i] = np.sign(self.W[i] @ s - threshold)
                        if s[i] == 0: s[i] = 1
                else:  # synchronous update
                    s = np.sign(self.W @ s - threshold)
                    s[s == 0] = 1
                e_new = self.energy(s)
                e_list.append(e_new)
                if e_new == e_list[-2]:  # stop if energy converged
                    break
            pred.append(s)
            energies.append(e_list)
        return pred, energies

def energy(self, s):
  return -0.5 * s @ self.W @ s

import numpy as np

def adam_optimizer(w, dw, m, v, t, lr=0.01, beta1=0.9, beta2=0.999, eps=1e-8):
    # Step 1: Update biased first moment estimate
    m = beta1 * m + (1 - beta1) * dw

    # Step 2: Update biased second raw moment estimate (using power from your lab)
    v = beta2 * v + (1 - beta2) * np.power(dw, 2)

    # Step 3: Compute bias-corrected estimates
    m_hat = m / (1 - np.power(beta1, t))
    v_hat = v / (1 - np.power(beta2, t))

    # Step 4: Update weights (using sqrt from your lab)
    w = w - lr * m_hat / (np.sqrt(v_hat) + eps)

    return w, m, v

# --- Test Case: Minimizing a Quadratic Function f(x) = x^2 ---
# The goal is for the weight (x) to reach 0.0

# Initializing parameters
weight = 10.0 # Starting point
m = 0.0
v = 0.0
iterations = 100

print(f"{'Iteration':<15} | {'Weight (x)':<15} | {'Gradient (dw)':<15}")
print("-" * 50)

for t in range(1, iterations + 1):
    # Derivative of x^2 is 2x
    gradient = 2 * weight

    # Apply Adam Update
    weight, m, v = adam_optimizer(weight, gradient, m, v, t)

    # Print output every 20 iterations to show progress
    if t % 20 == 0 or t == 1:
        print(f"{t:<15} | {weight:<15.6f} | {gradient:<15.6f}")

print("-" * 50)
print(f"Final Weight after {iterations} iterations: {weight:.10f}")

import tensorflow as tf
from tensorflow.keras import layers, models
import numpy as np

# 1. Generate dummy data: 100 samples, 10 time-steps, 1 feature
X_train = np.random.rand(100, 10, 1)
y_train = np.random.rand(100, 1)

# 2. Build Model
model_rnn = models.Sequential([
    # We use LSTM here as it's more stable than SimpleRNN
    layers.LSTM(64, input_shape=(10, 1), activation='tanh'),
    layers.Dense(1)
])

model_rnn.compile(optimizer='adam', loss='mse')

# 3. Train
print("Starting training...")
model_rnn.fit(X_train, y_train, epochs=5, verbose=1)

import tensorflow as tf
from tensorflow.keras import layers, models

# Simple RNN Model
model_rnn = models.Sequential([
    # Input shape: (timesteps, features)
    layers.SimpleRNN(64, input_shape=(10, 1), activation='tanh'),
    layers.Dense(1)
])

model_rnn.compile(optimizer='adam', loss='mse')
model_rnn.summary()